version: "3"

services:
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - "pg_data:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

volumes:
  pg_data:
